services:
  rise-exercise:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for live reloading
      - ./src:/app/src:ro
      - ./package*.json:/app/package*.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      - NODE_ENV=development
    # Override the CMD to use tsx watch for development
    command: ["npx", "tsx", "watch", "src/index.ts"]
    # Keep container running for development
    stdin_open: true
    tty: true
